# Generated by Django 3.2.8 on 2021-10-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], default='easy', max_length=12),
        ),
        migrations.AlterField(
            model_name='technique',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='technique',
            name='type',
            field=models.CharField(choices=[('choke', 'choke'), ('sweep', 'sweep'), ('escape', 'escape'), ('joint_lock', 'joint_lock'), ('takedown', 'takedown'), ('mixed', 'mixed')], default='mixed', max_length=10),
        ),
    ]
