# Generated by Django 3.2.8 on 2021-10-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_technique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
